const Kendaraan = require('./Kendaraan.js')
const Mobil = require('./Mobil.js')
const Motor = require('./Motor.js')
const Sepeda = require('./Sepeda.js')

// let kendaraan = new Kendaraan("Mitsubishi")
// console.log(kendaraan.start())
// console.log(kendaraan.info())
// console.log(kendaraan.stop())

let mobil = new Mobil("Toyota Avanza")
console.log(mobil.start())
console.log(mobil.info())
console.log(mobil.stop())
console.log(mobil.info())
console.log()

let motor = new Motor("Honda Beat")
console.log(motor.start())
console.log(motor.info())
console.log(motor.stop())
console.log(motor.info())
console.log()

let sepeda = new Sepeda("Toyota Avanza")
console.log(sepeda.start())
console.log(sepeda.info())
console.log(sepeda.stop())
console.log(sepeda.info())
console.log()
